/*
 * Classroom License -- for classroom instructional use only.  Not for
 * government, commercial, academic research, or other organizational use.
 * File: doFilterf2502k.c
 *
 * MATLAB Coder version            : 3.3
 * C/C++ source code generated on  : 08-Jun-2018 12:28:53
 */

/* Include Files */
#include "rt_nonfinite.h"
#include "doFilterf2502k.h"
#include "doFilterf2502k_data.h"

/* Function Definitions */

/*
 * DOFILTER Filters input x and returns output y.
 * Arguments    : double x
 * Return Type  : double
 */
double doFilterf2502k(double x)
{
  double y;
  dsp_BiquadFilter_0 *obj;
  double stageIn;

  /*  MATLAB Code */
  /*  Generated by MATLAB(R) 9.2 and the DSP System Toolbox 9.4. */
  /*  Generated on: 30-May-2018 12:18:11 */
  /*  To generate C/C++ code from this function use the codegen command. */
  /*  Type 'help codegen' for more information. */
  obj = &Hd.cSFunObject;

  /* System object Outputs function: dsp.BiquadFilter */
  stageIn = obj->P3_RTP3COEFF[0U] * x;
  stageIn -= obj->P2_RTP2COEFF[0] * obj->W0_FILT_STATES[0];
  stageIn -= obj->P2_RTP2COEFF[1] * obj->W0_FILT_STATES[1];
  y = obj->P1_RTP1COEFF[0] * stageIn;
  y += obj->P1_RTP1COEFF[1] * obj->W0_FILT_STATES[0];
  y += obj->P1_RTP1COEFF[2] * obj->W0_FILT_STATES[1];
  obj->W0_FILT_STATES[1] = obj->W0_FILT_STATES[0];
  obj->W0_FILT_STATES[0] = stageIn;
  stageIn = obj->P3_RTP3COEFF[1U] * y;
  stageIn -= obj->P2_RTP2COEFF[2] * obj->W0_FILT_STATES[2];
  stageIn -= obj->P2_RTP2COEFF[3] * obj->W0_FILT_STATES[3];
  y = obj->P1_RTP1COEFF[3] * stageIn;
  y += obj->P1_RTP1COEFF[4] * obj->W0_FILT_STATES[2];
  y += obj->P1_RTP1COEFF[5] * obj->W0_FILT_STATES[3];
  obj->W0_FILT_STATES[3] = obj->W0_FILT_STATES[2];
  obj->W0_FILT_STATES[2] = stageIn;
  stageIn = obj->P3_RTP3COEFF[2U] * y;
  stageIn -= obj->P2_RTP2COEFF[4] * obj->W0_FILT_STATES[4];
  stageIn -= obj->P2_RTP2COEFF[5] * obj->W0_FILT_STATES[5];
  y = obj->P1_RTP1COEFF[6] * stageIn;
  y += obj->P1_RTP1COEFF[7] * obj->W0_FILT_STATES[4];
  y += obj->P1_RTP1COEFF[8] * obj->W0_FILT_STATES[5];
  obj->W0_FILT_STATES[5] = obj->W0_FILT_STATES[4];
  obj->W0_FILT_STATES[4] = stageIn;
  stageIn = obj->P3_RTP3COEFF[3U] * y;
  stageIn -= obj->P2_RTP2COEFF[6] * obj->W0_FILT_STATES[6];
  stageIn -= obj->P2_RTP2COEFF[7] * obj->W0_FILT_STATES[7];
  y = obj->P1_RTP1COEFF[9] * stageIn;
  y += obj->P1_RTP1COEFF[10] * obj->W0_FILT_STATES[6];
  y += obj->P1_RTP1COEFF[11] * obj->W0_FILT_STATES[7];
  obj->W0_FILT_STATES[7] = obj->W0_FILT_STATES[6];
  obj->W0_FILT_STATES[6] = stageIn;
  stageIn = obj->P3_RTP3COEFF[4U] * y;
  stageIn -= obj->P2_RTP2COEFF[8] * obj->W0_FILT_STATES[8];
  stageIn -= obj->P2_RTP2COEFF[9] * obj->W0_FILT_STATES[9];
  y = obj->P1_RTP1COEFF[12] * stageIn;
  y += obj->P1_RTP1COEFF[13] * obj->W0_FILT_STATES[8];
  y += obj->P1_RTP1COEFF[14] * obj->W0_FILT_STATES[9];
  obj->W0_FILT_STATES[9] = obj->W0_FILT_STATES[8];
  obj->W0_FILT_STATES[8] = stageIn;
  stageIn = obj->P3_RTP3COEFF[5U] * y;
  stageIn -= obj->P2_RTP2COEFF[10] * obj->W0_FILT_STATES[10];
  stageIn -= obj->P2_RTP2COEFF[11] * obj->W0_FILT_STATES[11];
  y = obj->P1_RTP1COEFF[15] * stageIn;
  y += obj->P1_RTP1COEFF[16] * obj->W0_FILT_STATES[10];
  y += obj->P1_RTP1COEFF[17] * obj->W0_FILT_STATES[11];
  obj->W0_FILT_STATES[11] = obj->W0_FILT_STATES[10];
  obj->W0_FILT_STATES[10] = stageIn;
  stageIn = obj->P3_RTP3COEFF[6U] * y;
  stageIn -= obj->P2_RTP2COEFF[12] * obj->W0_FILT_STATES[12];
  stageIn -= obj->P2_RTP2COEFF[13] * obj->W0_FILT_STATES[13];
  y = obj->P1_RTP1COEFF[18] * stageIn;
  y += obj->P1_RTP1COEFF[19] * obj->W0_FILT_STATES[12];
  y += obj->P1_RTP1COEFF[20] * obj->W0_FILT_STATES[13];
  obj->W0_FILT_STATES[13] = obj->W0_FILT_STATES[12];
  obj->W0_FILT_STATES[12] = stageIn;
  return y;
}

/*
 * File trailer for doFilterf2502k.c
 *
 * [EOF]
 */
